---
# tasks file to setup rpi for Crocodile Hunter

- name: Overclock rpi
  become: yes
  lineinfile:
    path: /boot/config.txt
    insertafter: '^\[pi4\]'
    line: 'over_voltage=6arm_freq=2147'

- name: Change hostname
  become: yes
  hostname: 
    name: crocodilehunter

- name: Add crocodilehunter to /etc/hosts JIC
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost crocodilehunter'
    state: present

- name: Configure Wifi
  when: configure_wifi
  become: yes
  template:
    src: ../templates/wpa_supplicant.conf
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    owner: root
    group: root
    mode: '0600'

- name: Unblock wifi interface with rfkill
  when: configure_wifi
  become: yes
  command: rfkill unblock all

- name: Activate wifi interface
  when: configure_wifi
  become: yes
  command: ifconfig wlan0 up

- name: Reboot the server and wait for it to come back up.
  become: yes
  reboot:
