---
# tasks file to setup rpi for Crocodile Hunter

- name: Overclock rpi
  become: yes
  lineinfile:
    path: /boot/config.txt
    insertafter: '^#uncomment to overclock the arm. 700 MHz is the default.'
    line: "{{ item }}"
  loop:
    - "over_voltage=6"
    - "arm_freq=1750"
    - "gpu_freq=750"

- name: Change hostname
  become: yes
  hostname: 
    name: crocodilehunter

- name: Add crocodilehunter to /etc/hosts JIC
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost crocodilehunter'
    state: present

- name: Apt update & upgrade
  become: yes
  apt:
    update_cache: yes
    upgrade: yes

- name: Reboot the server and wait for it to come back up.
  become: yes
  reboot:
