---
# tasks file to install bladerf from source

- name: Install dependencies
  become: yes
  apt:
    state: present
    pkg:
      - git
      - libusb-1.0-0-dev
      - libusb-1.0-0
      - build-essential
      - cmake
      - libncurses5-dev
      - libtecla1
      - libtecla-dev
      - pkg-config
      - wget
      - acl
      - python3-pybind11
      - libsndfile1-dev

- name: Ensure group "bladerf" exists
  become: yes
  group:
    name: bladerf
    state: present

- name: adding existing user pi to group bladerf
  become: yes
  user:
    name: pi
    groups: bladerf 
    append: yes

- name: Clone BladeRF source code
  git:
    repo: "https://github.com/Nuand/bladeRF.git"
    dest: /home/pi/bladerf

- name: Create build dir
  file:
    path: /home/pi/bladerf/host/build
    state: directory
    owner: pi
    mode: 0755

- name: Build BladeRF
  command: "cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DINSTALL_UDEV_RULES=ON ../ -DBLADERF_GROUP=bladerf"
  args:
    chdir: "/home/pi/bladerf/host/build"

- name: Make BladeRF
  command: "make"
  args:
    chdir: "/home/pi/bladerf/host/build"

- name: Install BladeRF
  become: yes
  command: "make install"
  args:
    chdir: "/home/pi/bladerf/host/build"

- name: Complete BladeRF install
  become: yes
  command: "ldconfig"
  args:
    chdir: "/home/pi/bladerf/host/build"
    
- name: Download FPGA for x40
  become: yes
  command: "curl {{ blade_fpga_url }} -o hostedx40-latest.rbf"
  args:
    chdir: "/home/pi"

- name: Download blade firmware
  become: yes
  command: "curl {{ blade_firmware_url }} -o bladeRF_fw_latest.img"
  args:
    chdir: "/home/pi"

- name: Pause for 5 minutes to build app cache
  pause:
    seconds: 10

- name: Install FPGA in Blade x40
  become: yes
  command: "bladeRF-cli -v critical -l hostedx40-latest.rbf"
  args:
    chdir: "/home/pi"

- name: Install Firmware in Blade x40
  become: yes
  command: "bladeRF-cli -f bladeRF_fw_latest.img"
  args:
    chdir: "/home/pi"

- name: Reboot the server and wait for it to come back up. Just to avoid asking the user to (re)connect the radio
  become: yes
  reboot:
